services:
  db:
    image: postgres:15
    container_name: ticket_postgres
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket_pass
      POSTGRES_DB: ticket_db
    ports:
      - "5432:5432"
    volumes:
      - ticket_db_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4:7
      container_name: ticket_pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin123
      ports:
        - "8080:80"
      depends_on:
        - db
      volumes:
        - pgadmin_data:/var/lib/pgadmin

volumes:
  ticket_db_data:
  pgadmin_data:


